"""
jarvis/core/tools/dynamic_executor.py
THE MOST IMPORTANT FILE. Executes dynamically generated Python code from LLM.
This is how NOVA can do ANYTHING — LLM writes code, this file runs it.
"""

import sys
import os
import io
import traceback
import threading
import importlib
from typing import Optional


class DynamicExecutor:
    """
    Executes Python code generated by the LLM in a controlled environment.
    
    Allowed modules: os, sys, subprocess, shutil, glob, json, re, time, datetime,
                     requests, httpx, socket, struct, webbrowser, pathlib,
                     pyautogui, psutil, pygetwindow, win32gui, win32api, 
                     win32clipboard, ctypes, PIL, cv2, base64, hashlib
    
    Execution timeout: 60 seconds (configurable)
    Max retries on error: 3 (LLM sees error, regenerates code)
    """
    
    ALLOWED_MODULES = [
        "os", "sys", "subprocess", "shutil", "glob", "json", "re", "time",
        "datetime", "pathlib", "math", "random", "hashlib", "base64",
        "socket", "struct", "webbrowser", "urllib", "http",
        "requests", "httpx",
        "pyautogui", "psutil", "pygetwindow",
        "ctypes", "win32gui", "win32api", "win32clipboard", "win32con",
        "PIL", "cv2", "numpy",
        "sqlite3", "csv", "xml", "html",
        "threading", "queue", "collections", "itertools", "functools",
        "textwrap", "string", "platform", "getpass",
    ]
    
    def __init__(self, timeout: int = 60):
        self.timeout = timeout
        self.last_result = None
        self.last_error = None
    
    def execute(self, code: str) -> dict:
        """
        Execute generated Python code.
        
        Returns:
            {
                "success": bool,
                "output": str,      # stdout capture
                "result": str,      # return value if any
                "error": str|None   # error message if failed
            }
        """
        # Capture stdout
        old_stdout = sys.stdout
        old_stderr = sys.stderr
        captured_output = io.StringIO()
        captured_error = io.StringIO()
        
        result = {"success": False, "output": "", "result": "", "error": None}
        
        # Execute in thread with timeout
        exec_complete = threading.Event()
        
        def _run():
            nonlocal result
            sys.stdout = captured_output
            sys.stderr = captured_error
            try:
                # Create execution namespace with common imports available
                exec_globals = {
                    "__builtins__": __builtins__,
                    "__name__": "__dynamic_exec__",
                }
                
                # Pre-import allowed modules into namespace
                for mod_name in self.ALLOWED_MODULES:
                    try:
                        mod = importlib.import_module(mod_name)
                        # Use last part of name as variable (e.g., scapy.all -> all)
                        short_name = mod_name.split('.')[-1]
                        exec_globals[short_name] = mod
                    except ImportError:
                        pass
                
                exec(code, exec_globals)
                
                # Check if there's a 'result' variable in the executed code
                if 'result' in exec_globals:
                    result["result"] = str(exec_globals['result'])
                
                result["success"] = True
                
            except Exception as e:
                result["error"] = f"{type(e).__name__}: {str(e)}\n{traceback.format_exc()}"
            finally:
                sys.stdout = old_stdout
                sys.stderr = old_stderr
                result["output"] = captured_output.getvalue()
                if captured_error.getvalue():
                    result["output"] += "\nSTDERR:\n" + captured_error.getvalue()
                exec_complete.set()
        
        thread = threading.Thread(target=_run, daemon=True)
        thread.start()
        
        # Wait with timeout
        completed = exec_complete.wait(timeout=self.timeout)
        
        if not completed:
            result["success"] = False
            result["error"] = f"Execution timed out after {self.timeout} seconds"
            # Restore stdout/stderr in case thread is still running
            sys.stdout = old_stdout
            sys.stderr = old_stderr
        
        self.last_result = result
        return result
